version: '3'
services:
  db:
    image: mtirsel/mysql-5.1
    container_name: db-51
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbname
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
  php:
    build: ./php
    container_name: php-54
    volumes:
      - ./public:/usr/local/apache2/htdocs
    depends_on:
      - db
  web:
    image: httpd:2.4
    container_name: web-24
    ports:
      - "80:80"
    volumes:
      - ./public:/usr/local/apache2/htdocs
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./httpd/httpd-vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
    depends_on:
      - php
    
